# sezioni aggiuntive del test master (caricate da ui_master.py)
import math
async def run(T):
  pg,ev,S,X,Y,bands,clear,mk,node,ok=T['pg'],T['ev'],T['S'],T['X'],T['Y'],T['bands'],T['clear'],T['mk'],T['node'],T['ok']
  print('== P0.1 Decadimento spettro indipendente dagli fps ==')
  for fps in (30,60,120):
    r=await ev(f"""(()=>{{const G=window.__tsrq.graph, real=performance.now.bind(performance); let t=1e6; performance.now=()=>t; G.tSpec=undefined; G.decay=40; G.avg=0.3; G.freeze=false;
      const n=1024, loud=new Float32Array(n/2).fill(0), quiet=new Float32Array(n/2).fill(-200); for(let k=0;k<30;k++){{t+=1000/{fps}; G.feedSpec(loud,loud,n);}}
      let t0=t, s=null; for(let k=0;k<{fps}*5;k++){{t+=1000/{fps}; G.feedSpec(quiet,quiet,n); const v=G._specPost()[100]; if(s===null&&v<=-40){{s=(t-t0)/1000;}}}} performance.now=real; return s;}})()""")
    T.setdefault('dec',[]).append(r); ok(r is not None and abs(r-1.0)<0.05,f"{fps} fps: da 0 a -40 dB in {r} s (atteso 1.00 s a 40 dB/s)")
  d=T['dec']; ok(max(d)-min(d)<0.05,f"stesso tempo a 30/60/120 fps (scarto {max(d)-min(d):.3f} s)")
  r=await ev("""(()=>{const G=window.__tsrq.graph, real=performance.now.bind(performance); let t=2e6; performance.now=()=>t; G.tSpec=undefined; const n=1024, loud=new Float32Array(n/2).fill(0), quiet=new Float32Array(n/2).fill(-200);
    for(let k=0;k<30;k++){t+=16.7; G.feedSpec(loud,loud,n);} t+=3000; G.feedSpec(quiet,quiet,n); const v=G._specPost()[100]; performance.now=real; return v;})()""")
  ok(r<=-119,f"pausa UI di 3 s: alla ripresa lo spettro e gia sceso di 120 dB ({r:.1f} dB), non si blocca")
  print('== P0.2 Gesti di automazione (lato interfaccia) ==')
  await clear(); a=await mk(1000,2); await ev("window.__tsrqGestLog.length=0"); sx,sy=await node(a)
  await pg.mouse.move(sx,sy); await pg.mouse.down(); await pg.mouse.move(sx+50,sy-30,steps=12); await pg.mouse.up(); await pg.wait_for_timeout(120)
  lg=(await ev("window.__tsrq.gesture()"))['log']; ok(lg==['begin','end'],f"trascinamento con 12 movimenti: un solo inizio e una sola fine ({lg})")
  await ev("window.__tsrqGestLog.length=0"); sx,sy=await node(a); await pg.mouse.move(sx,sy)
  for k in range(5): await pg.mouse.wheel(0,-100); await pg.wait_for_timeout(40)
  await pg.wait_for_timeout(500); lg=(await ev("window.__tsrq.gesture()"))['log']; ok(lg==['begin','end'],f"5 scatti di rotellina ravvicinati: un gesto ({lg})")
  await ev("window.__tsrqGestLog.length=0"); await pg.mouse.move(sx,sy); await pg.mouse.down(); await pg.mouse.move(sx+30,sy,steps=4); await ev("window.dispatchEvent(new Event('blur'))"); await pg.mouse.up(); await pg.wait_for_timeout(100)
  lg=(await ev("window.__tsrq.gesture()")); ok(lg['log'][:2]==['begin','end'] and not lg['open'],f"perdita del focus durante il trascinamento: gesto chiuso ({lg['log']})")
  print('== P1.5 Zoom e pan delle frequenze ==')
  v0=await ev("window.__tsrq.graph.view()"); f1k=await ev("window.__tsrq.graph.X(1000)"); x,y=S(f1k,520)
  await pg.mouse.move(x,y); await pg.mouse.down(); await pg.mouse.move(x,y-120,steps=8); await pg.mouse.up(); await pg.wait_for_timeout(150)
  v1=await ev("window.__tsrq.graph.view()"); xa=await ev("window.__tsrq.graph.X(1000)")
  ok(math.log(v1['hi']/v1['lo'])<math.log(v0['hi']/v0['lo'])*0.5 and abs(xa-f1k)<1.0,f"trascina in su sulla scala: zoom ({v1['lo']:.0f}–{v1['hi']:.0f} Hz), 1 kHz resta sotto il puntatore (scarto {abs(xa-f1k):.2f} px)")
  P0=await ev("JSON.stringify(window.__tsrq.P())"); await pg.mouse.move(x,y); await pg.mouse.down(); await pg.mouse.move(x-200,y,steps=8); await pg.mouse.up(); await pg.wait_for_timeout(150)
  v2=await ev("window.__tsrq.graph.view()"); ok(v2['lo']>v1['lo'] and abs(math.log(v2['hi']/v2['lo'])-math.log(v1['hi']/v1['lo']))<1e-6,f"trascina a sinistra: pan ({v2['lo']:.0f}–{v2['hi']:.0f} Hz), ampiezza invariata")
  ok(await ev("JSON.stringify(window.__tsrq.P())")==P0,'zoom e pan non cambiano nessun parametro audio')
  n=await ev(f"window.__tsrq.graph.nodePos({a})"); ok(abs(n['x']-await ev("window.__tsrq.graph.X(window.__tsrq.P().bands[0].freq)"))<1e-6,'il nodo usa la stessa trasformazione della griglia')
  await pg.mouse.move(x,y); await pg.mouse.wheel(0,500); await pg.wait_for_timeout(100); await pg.mouse.dblclick(x,y); await pg.wait_for_timeout(150)
  v3=await ev("window.__tsrq.graph.view()"); ok(abs(v3['lo']-10)<1e-6 and v3['hi']>=20000,f"doppio clic sulla scala: vista completa ({v3['lo']:.0f}–{v3['hi']:.0f} Hz)")
  for k in range(30): await ev("window.__tsrq.graph.setView(5, 100000)")
  v4=await ev("window.__tsrq.graph.view()"); ok(v4['lo']>=10 and v4['hi']<=30000,f"pan/zoom limitati all'intervallo utile ({v4['lo']}–{v4['hi']:.0f})")
  print('== P1.7 Split ==')
  await clear(); a=await mk(800,5); await ev(f"window.__tsrq.graph.selectOnly({a})"); u0=await ev("window.__tsrq.undoLen()")
  await ev("window.__tsrq.graph.split(1,2)"); bs=await bands(); ok(len(bs)==2 and sorted([x['p'] for x in bs])==[1,2] and all(abs(x['f']-800)<1e-9 and abs(x['g']-5)<1e-9 for x in bs) and bs[0]['i']!=bs[1]['i'],f"Split L/R: due bande Left/Right con gli stessi parametri e ID diversi ({[(x['i'],x['p']) for x in bs]})")
  ok(await ev("window.__tsrq.undoLen()")-u0==1,'Split = un solo passo di undo'); await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(100); bs=await bands(); ok(len(bs)==1 and bs[0]['p']==0,'undo: torna una banda Stereo')
  r=await ev("""(()=>{const T=TSRQ,fs=48000,n=48000,mk=()=>{const L=new Float32Array(n),R=new Float32Array(n);let s=1;for(let i=0;i<n;i++){s=(s*16807)%2147483647;L[i]=(s/2147483647-.5)*.5;s=(s*16807)%2147483647;R[i]=(s/2147483647-.5)*.5;}return[L,R]};
    const run=(bands)=>{const e=new T.Engine(fs,512),[L,R]=mk();const st={bands,inGain:0,out:0,autoGainDb:0,scale:1,character:0,bypass:false,solo:-1};for(let i=0;i<n;i+=512){e.setState(st);e.process(L.subarray(i,i+512),R.subarray(i,i+512),512);}return[L,R]};
    const b=(id,pl)=>({id,on:true,type:'bell',f:800,q:1.3,g:5,slope:12,place:pl,dyn:{on:false}});
    const [a1,a2]=run([b(0,0)]),[c1,c2]=run([b(0,1),b(1,2)]),[d1,d2]=run([b(0,3),b(1,4)]);let m1=0,m2=0;for(let i=0;i<n;i++){m1=Math.max(m1,Math.abs(a1[i]-c1[i]),Math.abs(a2[i]-c2[i]));m2=Math.max(m2,Math.abs(a1[i]-d1[i]),Math.abs(a2[i]-d2[i]));}return [20*Math.log10(m1+1e-30),20*Math.log10(m2+1e-30)];})()""")
  ok(r[0]<-120 and r[1]<-120,f"Split conserva il suono (motore audio, rumore stereo): L/R residuo {r[0]:.0f} dBFS, M/S residuo {r[1]:.0f} dBFS")
  await clear(); [await mk(100+i*50,0) for i in range(31)]; await ev("window.__tsrq.graph.selectAll()"); await ev("window.__tsrq.graph.split(1,2)"); ok(len(await bands())==31,'Split con bande libere insufficienti: rifiutato, nessuna banda persa')
  print('== Pannello USCITA, A/B, isola ==')
  await clear(); await ev("window.__tsrqOutPanel(400,200)"); await pg.wait_for_timeout(100)
  await pg.locator('.outp [data-a=ms]').click(); await pg.locator('.outp [data-a=inv]').click(); await pg.locator('.outp [data-a=c2]').click(); await pg.locator('.outp [data-a=gq]').click()
  sl=await pg.locator('.outp input[data-a=pan]').bounding_box(); await pg.mouse.click(sl['x']+sl['width']*0.75,sl['y']+sl['height']/2); await pg.wait_for_timeout(150)
  P1=await ev("(()=>{const P=window.__tsrq.P();return {pan:P.pan,ms:P.panMS,inv:P.inv,ch:P.char,gq:P.gq}})()")
  ok(P1['ms']==1 and P1['inv']==1 and P1['ch']==2 and P1['gq']==1 and 40<P1['pan']<60,f"pannello USCITA → parametri ({P1})")
  st=await ev("(()=>{let m=null;const o=window.__tsrqHost;return null})()")
  await ev("dirty=true; flush()"); eng=await ev("(()=>{const b=graph.selection();return engineBand? 1:0})()")
  ab=await ev("(()=>{bA.onclick();const s0=abSlot;bB.onclick();return [s0,abSlot]})()"); ok(ab==[0,1],f'A/B dal menu: passa da A a B ({ab})')
  await ev("bA.onclick()"); await pg.keyboard.press('Escape')
  await pg.mouse.click(5,5); await clear(); a=await mk(300,-8); await ev(f"window.__tsrq.graph.selectOnly({a})"); await pg.wait_for_timeout(400)
  pos=await ev("window.__tsrq.islandPos()"); nb=await ev(f"(()=>{{const n=window.__tsrq.graph.nodePos({a}),e=document.elementFromPoint(0,0);const r=document.querySelector('.graph canvas').getBoundingClientRect();return [n.x*r.width/1160+r.left,n.y*r.height/532+r.top]}})()")
  el=await ev(f"document.elementFromPoint({nb[0]},{nb[1]}).className"); ok(pos=='top' and 'bisl' not in str(el),f"nodo che finirebbe sotto l'isola: l'isola sale in alto ({pos}), il nodo resta cliccabile ({el or 'canvas'})")
  print('== Grab, piano, sketch ==')
  await clear(); await ev("window.__tsrq.play()"); await pg.wait_for_timeout(2500)
  x=await ev("window.__tsrq.graph.X(400)"); sy=await ev("window.__tsrq.graph.AY(window.__tsrq.graph.specDb(window.__tsrq.graph.X(400)))"); px_,py_=S(x,sy+40)
  await pg.mouse.move(px_,py_); await pg.mouse.move(px_+2,py_+1); await pg.wait_for_timeout(1500)
  gr=await ev("window.__tsrq.grab()"); ok(gr['on'],f"cursore fermo sullo spettro 1,5 s: Spectrum Grab attivo ({gr})")
  ok(await ev("window.__tsrq.graph.hold===true && window.__tsrq.graph.dimBands===true"),'vista congelata e bande attenuate')
  await pg.mouse.down(); await pg.mouse.move(px_+5,py_+60,steps=8); await pg.mouse.up(); await pg.wait_for_timeout(200)
  bs=await bands(); gr=await ev("window.__tsrq.grab()"); ok(len(bs)==1 and bs[0]['g']<-1 and not gr['on'],f"trascino dal picco: Bell che taglia ({[(round(b['f']),b['g']) for b in bs]}), al rilascio Grab finito ({gr})")
  await ev("window.__tsrq.graph.selectOnly(-1)"); await pg.wait_for_timeout(300); await ev("window.__tsrqGrabEnter()"); await pg.mouse.move(px_,py_+10); await pg.mouse.down(); await pg.wait_for_timeout(900); await pg.mouse.up(); gr=await ev("window.__tsrq.grab()"); ok(gr['on'] and gr['pers'],f"tieni premuto 0,9 s: modalità persistente ({gr})")
  await pg.mouse.click(px_+80,py_+10); await pg.wait_for_timeout(100); gr=await ev("window.__tsrq.grab()"); ok(not gr['on'] and not await ev("window.__tsrq.graph.hold"),f"clic sullo sfondo: esce ({gr})")
  await clear(); await ev("window.__tsrqTools.key(true)"); a=await mk(437,0); await pg.wait_for_timeout(150)
  kx=await ev(f"window.__tsrq.graph.X(437)"); ky=532-22-22+11; await pg.mouse.move(*S(kx,ky)); await pg.mouse.down(); await pg.wait_for_timeout(50)
  f1=(await bands())[0]['f']; a5=await ev("window.__tsrq.graph.X(880)"); await pg.mouse.move(*S(a5,ky),steps=10); await pg.mouse.up(); await pg.wait_for_timeout(100); f2=(await bands())
  ok(abs(f1-440)<1e-6,f"piano: clic sul punto della banda (437 Hz) → intonata a A4 {f1:.2f} Hz"); ok(len(f2)==1 and abs(f2[0]['f']-880)<1e-6,f"piano: trascinata a semitoni fino a A5 ({f2[0]['f']:.2f} Hz)")
  await ev("window.__tsrqTools.key(false)"); await clear()
  r=await ev("""(()=>{window.__tsrqTools.pen(true);const ov=document.querySelector('.graph .ovl'),R=ov.getBoundingClientRect(),G=window.__tsrq.graph,ev=(t,x,y)=>ov.dispatchEvent(new PointerEvent(t,{clientX:R.left+x*R.width/1160,clientY:R.top+y*R.height/532,bubbles:true,pointerId:1,buttons:t==='pointerup'?0:1}));
    const y0=G.Y(0),y6=G.Y(6);ev('pointerdown',G.X(50),y0);for(let f=50;f<=3000;f*=1.1)ev('pointermove',G.X(f),G.Y(-6*Math.exp(-Math.pow(Math.log2(f/350)/0.8,2))));for(let f=3000;f>=150;f/=1.1)ev('pointermove',G.X(f),y0);for(let f=150;f<=3000;f*=1.1)ev('pointermove',G.X(f),G.Y(6*Math.exp(-Math.pow(Math.log2(f/350)/0.8,2))));ev('pointerup',G.X(3000),y0);window.__tsrqTools.pen(false);
    return window.__tsrq.P().bands.filter(b=>b.used).map(b=>[Math.round(b.freq),+b.gain.toFixed(1)])})()""")
  ok(len(r)>=1 and all(g>0 for f,g in r) and len(r)<=3,f"Sketch: campana −6 dB, poi indietro e ridisegnata +6 dB → solo bande positive, poche ({r})")
  print('== Analizzatore: range, tilt, Pre tratteggiato, nessun ingresso, freeze ==')
  await ev("window.__tsrq.graph.selectAll(); window.__tsrq.graph.deleteSelected()")
  ay=await ev("[(()=>{const G=window.__tsrq.graph;G.anaRange=60;return G.AY(-60)})(),(()=>{const G=window.__tsrq.graph;G.anaRange=120;return G.AY(-60)})(),(()=>{const G=window.__tsrq.graph;G.anaRange=90;return G.AY(-90)})()]")
  pl=await ev("[window.__tsrq.graph.PL.y, window.__tsrq.graph.PL.h]"); ok(abs(ay[0]-(pl[0]+pl[1]))<1e-6 and ay[1]<ay[0] and abs(ay[2]-(pl[0]+pl[1]))<1e-6,f"range analizzatore 60/90/120 dB: fondo scala corretto ({[round(v,1) for v in ay]})")
  t=await ev("(()=>{const G=window.__tsrq.graph;const x=G.X(4000);G.tilt=0;const a=G.specDb(x);G.tilt=4.5;const b=G.specDb(x);return [a,b]})()"); ok(abs((t[1]-t[0])-4.5*2)<1e-6,f"tilt 4.5 dB/ottava: a 4 kHz +{t[1]-t[0]:.2f} dB (2 ottave sopra 1 kHz) solo nel disegno")
  au=await ev("""(()=>{const e=new TSRQ.Engine(48000,512);return 1})()"""); 
  frz=await ev("""(()=>{const G=window.__tsrq.graph,n=1024,a=new Float32Array(n/2).fill(-20),b=new Float32Array(n/2).fill(-60);G.freeze=true;G.feedSpec(a,a,n);G.feedSpec(b,b,n);const v=G._specPost()[50];G.freeze=false;return v})()""")
  ok(abs(frz+20)<1e-6,f"FREEZE: trattiene e accumula i massimi (-20 dB resta dopo un frame a -60: {frz})")
  await ev("stopSrc()"); await pg.wait_for_timeout(200)
  ni=await ev("(()=>{const G=window.__tsrq.graph;return G.noInput})()"); ok(ni is True,'audio fermo: stato "nessun audio" esplicito, nessuna animazione finta')
  print('== Waveform ==')
  await ev("stopSrc()"); await pg.wait_for_timeout(200)
  r=await ev("""(()=>{const W=window.__tsrq.wave;W.open(true);const n=750*2,w=new Float32Array(n*8);for(let k=0;k<n;k++){const v=(k===700)?0.9:0.1;w.set([-v,v,-v,v,-v/2,v/2,-v/2,v/2],k*8);}const h0=W.state().head;window.__tsrqWaveIn(w,{B:64,fs:48000,playing:true,drop:0,jumps:0});return [W.state().head-h0]})()""")
  ok(r[0]==1500,f"inviluppo ricevuto: 1500 gruppi (2 s @48k)")
  await pg.wait_for_timeout(300); pk=await ev("window.__tsrq.wave.state().peak"); ok(abs(pk-0.45)<1e-6,f"il picco isolato di un solo gruppo (64 campioni) resta visibile dopo la riduzione per pixel (picco post {pk:.3f}, atteso 0.450)")
  r=await ev("""(()=>{const W=window.__tsrq.wave,h=W.state().head;window.__tsrqWaveIn(new Float32Array(16).fill(0.2),{B:64,fs:48000,playing:true,drop:5,jumps:1});return [W.state().head-h, isNaN(W.ring(h,0)), W.mark(h+5)]})()""")
  ok(r[0]==7 and r[1] and r[2]==1,f"5 gruppi persi = buco dichiarato (NaN, niente campioni inventati) e salto di trasporto segnato ({r})")
  r=await ev("""(()=>{const W=window.__tsrq.wave,h=W.state().head;window.__tsrqWaveIn(new Float32Array(80),{B:64,fs:48000,playing:false,drop:0,jumps:1});const a=[W.state().head-h,W.state().hold];window.__tsrqWaveIn(new Float32Array(80).fill(.3),{B:64,fs:48000,playing:false,drop:0,jumps:1});return a.concat([W.state().head-h,W.state().live])})()""")
  ok(r[0]==0 and r[1] and r[2]==10 and r[3],f"trasporto fermo: silenzio = HOLD (il tempo si ferma), ingresso presente = LIVE ({r})")
  await ev("window.__tsrq.wave.set({frz:true, frzHead: window.__tsrq.wave.state().head})"); h=await ev("window.__tsrq.wave.state().head"); await ev("window.__tsrqWaveIn(new Float32Array(80).fill(.1),{B:64,fs:48000,playing:true,drop:0,jumps:1})")
  ok(await ev("window.__tsrq.wave.state().head")==h+10,'FREEZE blocca la vista, non i dati (il buffer continua a riempirsi)'); await ev("window.__tsrq.wave.set({frz:false})")
  await ev("window.__tsrq.play()"); await pg.wait_for_timeout(1500); h1=await ev("window.__tsrq.wave.state().head"); await pg.wait_for_timeout(1000); h2=await ev("window.__tsrq.wave.state().head")
  gps=(h2-h1)/1.0; fs=await ev("ctx.sampleRate"); ok(abs(gps-fs/64)/(fs/64)<0.15,f"audio reale dal motore: {gps:.0f} gruppi/s (atteso {fs/64:.0f} = fs/64): scorrimento a tempo")
  await pg.screenshot(path='m_wave.png')
  await pg.locator('.wpan [data-v=spec]').click(); await pg.wait_for_timeout(1500); c=await ev("window.__tsrq.wave.state().cols")
  ok(c>W_ if (W_:=50) else False,f"spettrogramma: colonne disegnate dai dati STFT reali ({c} px)"); await pg.screenshot(path='m_spec.png'); await ev("window.__tsrq.wave.open(false)")
  print('== EQ Match ==')
  r=await ev("""(()=>{const M=window.__tsrqMatch,GN=240,ref=new Float64Array(GN),inp=new Float64Array(GN);for(let i=0;i<GN;i++){const f=20*Math.pow(1000,i/(GN-1));ref[i]=-30+6*Math.exp(-Math.pow(Math.log2(f/2500)/0.6,2));inp[i]=-40;}M._set({ref:{grid:ref,src:'test'},inp:{grid:inp}});M.setDetail(6);return M.state()})()""")
  ok(r['prop'] and len(r['prop'])>=1 and abs(r['prop'][0][0]-2500)/2500<0.1 and r['prop'][0][1]>4 and r['resid']<1.5,f"riferimento con +6 dB a 2,5 kHz (livello diverso di 10 dB): proposta {r['prop']}, scarto {r['resid']:.2f} dB")
  r2=await ev("(()=>{window.__tsrqMatch.setDetail(1);return window.__tsrqMatch.state()})()"); ok(len(r2['prop'])==1,f"dettaglio 1: una sola banda ({r2['prop']})")
  u0=await ev("window.__tsrq.undoLen()"); await ev("window.__tsrqMatch.setDetail(6); window.__tsrqMatch.apply()"); bs=await bands(); ok(len(bs)==len(r['prop']) and await ev("window.__tsrq.undoLen()")-u0==1,f"applica: {len(bs)} bande, un passo di undo")
  await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(100); ok(len(await bands())==0,'undo: proposta rimossa')
  await ev("stopSrc()"); await pg.wait_for_timeout(300); r=await ev("""new Promise(res=>{const M=window.__tsrqMatch;M._set({ref:null,inp:null});const G=window.__tsrq.graph,n=1024,q=new Float32Array(n/2).fill(-200);M.capture('ref',0.3);const t=setInterval(()=>G.onRaw(q,q,n,48000),20);setTimeout(()=>{clearInterval(t);res(M.state())},600)})""")
  ok(not r['ref'] and 'insufficiente' in r['msg'],f"riferimento in silenzio: rifiutato con messaggio ('{r['msg']}')")
