# test delle funzioni nuove (dal video): menu destro, dinamica visibile, selezione multipla, picchi dello spettro, pendenze 96, zona tagliata rossa
import asyncio, sys
from playwright.async_api import async_playwright
URL='http://localhost:8770/TSR_Q_09_ceramica_smart.html'; res=[]
def ok(c,m): res.append(bool(c)); print(('PASS ' if c else 'FAIL ')+m)
async def main():
  async with async_playwright() as p:
    br=await p.chromium.launch(executable_path='/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args=['--autoplay-policy=no-user-gesture-required'])
    pg=await br.new_page(viewport={'width':1300,'height':720}); errs=[]; pg.on('pageerror',lambda e:errs.append(str(e)))
    await pg.goto(URL); await pg.wait_for_timeout(600); ev=pg.evaluate
    g=await pg.locator('.graph canvas:not(.ovl)').bounding_box(); S=lambda x,y:(g['x']+x/1160*g['width'],g['y']+y/532*g['height'])
    X=lambda f: ev(f'window.__tsrq.graph.X({f})'); Y=lambda d: ev(f'window.__tsrq.graph.Y({d})')
    bands=lambda: ev("window.__tsrq.P().bands.map((b,i)=>b.used?{i,t:b.type,f:b.freq,g:b.gain,q:b.q,s:b.slope,d:b.dyn,r:b.range}:null).filter(Boolean)")
    clear=lambda: ev("window.__tsrq.graph.selectAll(); window.__tsrq.graph.deleteSelected()")
    mk=lambda f,gd,t=0: ev(f"window.__tsrq.graph.createBand({f},{gd},{t})")
    async def menu(i):
      n=await ev(f"window.__tsrq.graph.nodePos({i})"); await pg.mouse.click(*S(n['x'],n['y']),button='right'); await pg.wait_for_timeout(200)
    async def pick(txt):
      await pg.locator('.pm .pm-i',has_text=txt).first.click(); await pg.wait_for_timeout(200)
    print('== 1. Menu tasto destro ==')
    await clear(); a=await mk(1000,4); await menu(a)
    items=await ev("[...document.querySelectorAll('.pm .pm-i')].map(x=>x.innerText.replace(/[✓›\\n]/g,'').trim())")
    ok(all(t in items for t in ['Tipo di filtro','Pendenza','Lavora su','Dinamica','Bypass banda','Solo banda','Inverti guadagno','Copia','Incolla','Elimina']),f'voci del menu ({items})')
    await pick('Inverti guadagno'); b=(await bands())[0]; ok(abs(b['g']+4)<1e-9,f"Inverti guadagno: +4 → {b['g']} dB")
    await menu(a); await pick('Copia'); await menu(a); await pick('Incolla'); bs=await bands()
    ok(len(bs)==2 and all(abs(x['f']-1000)<1e-6 and abs(x['g']+4)<1e-9 for x in bs),f'Copia + Incolla: 2 bande uguali ({len(bs)})')
    await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(150); ok(len(await bands())==1,'undo dell\'incolla')
    await menu(a); await pick('Elimina'); ok(len(await bands())==0,'Elimina dal menu')
    a=await mk(500,0,6); await menu(a); await pg.locator('.pm .pm-i',has_text='Pendenza').first.hover(); await pg.wait_for_timeout(250)
    sl=await ev("[...document.querySelectorAll('.pm')].pop().innerText.replace(/✓/g,'').split('\\n').map(s=>s.trim()).filter(Boolean)")
    ok(sl[-1]=='96 dB/oct' and '72 dB/oct' in sl,f'Band Pass: pendenze nel menu fino a 96 ({sl})'); await pick('96 dB/oct')
    ok((await bands())[0]['s']==8,'Band Pass impostato a 96 dB/oct (indice 8)')
    await pg.keyboard.press('Escape')
    print('== 2. Pendenze 96 + zona tagliata rossa ==')
    lst=await ev("""(()=>{const G=window.__tsrq.graph;return null})()""")
    bi=(await bands())[0]['i']; await ev(f"window.__tsrq.graph.selectOnly({bi})"); n=await ev(f"window.__tsrq.graph.nodePos({bi})"); await pg.mouse.move(*S(n['x'],n['y']))
    for k in range(4): await pg.mouse.wheel(0,100); await pg.wait_for_timeout(80)
    ok((await bands())[0]['s']<8,f"rotella sul Band Pass scende da 96 ({(await bands())[0]['s']})")
    for k in range(6): await pg.mouse.wheel(0,-100); await pg.wait_for_timeout(80)
    ok((await bands())[0]['s']==8,f"rotella sul Band Pass risale e si ferma a 96 ({(await bands())[0]['s']})")
    await clear(); c=await mk(6000,0,4); await ev(f"window.__tsrq.P().bands[{c}].slope=8; dirty=true"); await pg.wait_for_timeout(300)
    px=await ev(f"""(()=>{{const cv=document.querySelector('.graph canvas:not(.ovl)'),G=window.__tsrq.graph,x=Math.round(G.X(15000)*cv.width/1160),y=Math.round(G.Y(-6)*cv.height/532);const d=cv.getContext('2d').getImageData(x,y,1,1).data;return [...d]}})()""")
    ok(px[0]>px[2]+25 and px[0]>px[1]+15,f'High Cut 96 dB/oct: zona tagliata rossa (pixel a 15 kHz −6 dB = {px[:3]})')
    await pg.screenshot(path='nw_cut.png')
    await pg.mouse.move(*S(300,60)); await ev(f"window.__tsrq.graph.selectOnly(-1)"); await pg.wait_for_timeout(200)
    px2=await ev(f"""(()=>{{const cv=document.querySelector('.graph canvas:not(.ovl)'),G=window.__tsrq.graph,x=Math.round(G.X(15000)*cv.width/1160),y=Math.round(G.Y(-6)*cv.height/532);const d=cv.getContext('2d').getImageData(x,y,1,1).data;return [...d]}})()""")
    ok(px2[0]<px[0],f'zona rossa piu tenue quando la banda non e selezionata ({px2[:3]})')
    print('== 3. Dinamica visibile ==')
    await clear(); a=await mk(800,3); await ev(f"(()=>{{const b=window.__tsrq.P().bands[{a}];b.dyn=1;b.range=-1.5;dirty=true}})()"); await pg.wait_for_timeout(900)  # l'isola compare con un'animazione: misuro il knob a fermo
    r=await ev("window.__tsrq.gainRing()"); ok(r and r['ring'],f'anello range sul knob GAIN visibile ({r})')
    kg=await ev("(()=>{const c=[...document.querySelectorAll('.bisl canvas.knob')].find(c=>c.classList.contains('ring'));const r=c.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}})()")
    cx=kg['x']+kg['w']/2; top=kg['y']+kg['h']*(77/2-(min(73,77)-6)/2-3.8)/77
    await pg.mouse.move(cx,top); await pg.mouse.down(); await pg.mouse.move(cx,top-40,steps=6); await pg.mouse.up(); await pg.wait_for_timeout(200)
    b=(await bands())[0]; ok(b['r']>-1.5 and abs(b['g']-3)<1e-9,f"trascino l'anello in su: range -1.5 → {b['r']} dB, guadagno fermo {b['g']}")
    await pg.mouse.move(cx,top); await pg.mouse.down(); await pg.mouse.move(cx,top-400,steps=6); await pg.mouse.up(); await pg.wait_for_timeout(200)
    b=(await bands())[0]; ok(abs(b['r']-1.5)<1e-9,f"anello tirato molto in su: range fermo a +1.5 dB ({b['r']})")
    await pg.mouse.move(cx,kg['y']+kg['h']/2); await pg.mouse.down(); await pg.mouse.move(cx+20,kg['y']+kg['h']/2-20,steps=6); await pg.mouse.up(); await pg.wait_for_timeout(200)
    b2=(await bands())[0]; ok(b2['g']>3 and b2['r']==b['r'],f"centro del knob: cambia il guadagno ({b2['g']:.2f}), non il range")
    await pg.screenshot(path='nw_dyn.png', clip={'x':kg['x']-30,'y':kg['y']-20,'width':kg['w']+60,'height':kg['h']+40})
    print('== 4. Selezione multipla ==')
    await clear(); ids=[await mk(f,gd) for f,gd in [(150,-3),(700,2),(4000,-2)]]
    x0,y0=S(await X(60),40); x1,y1=S(await X(2000),480)
    await pg.mouse.move(x0,y0); await pg.mouse.down(); await pg.mouse.move(x1,y1,steps=10); await pg.mouse.up(); await pg.wait_for_timeout(250)
    sel=await ev("window.__tsrq.graph.selection()"); ok(sorted(sel)==sorted(ids[:2]),f'rettangolo seleziona le bande dentro ({sel})')
    ok(await ev("window.__tsrq.multiBadge()")=='2 BANDE','isola: etichetta "2 BANDE"')
    bs0=await bands(); n=await ev(f"window.__tsrq.graph.nodePos({ids[1]})"); sx,sy=S(n['x'],n['y'])
    await pg.mouse.move(sx,sy); await pg.mouse.down(); await pg.mouse.move(sx,sy-40,steps=6); await pg.mouse.up(); await pg.wait_for_timeout(200); bs1=await bands()
    d=[bs1[k]['g']-bs0[k]['g'] for k in range(3)]; ok(d[0]>0.5 and abs(d[0]-d[1])<1e-6 and abs(d[2])<1e-9,f'trascinando una, le 2 selezionate si muovono insieme (Δ {d[0]:.2f}, {d[1]:.2f}, {d[2]:.2f})')
    await ev("window.__tsrq.graph.selectOnly(0)"); await pg.wait_for_timeout(150); ok(await ev("window.__tsrq.multiBadge()") is None,'con una sola banda l\'etichetta sparisce')
    print('== 5. Picchi dello spettro ==')
    await clear(); await ev("window.__tsrq.play()"); await pg.wait_for_timeout(6000)
    pk=await ev("window.__tsrq.peaks()"); ok(1<=len(pk)<=5,f"etichette sui picchi: {len(pk)} ({[round(x['f']) for x in pk]})")
    near=[x for x in pk if abs(x['f']-2730)/2730<0.04]; ok(len(near)==1,'trovata la risonanza a 2730 Hz del segnale di prova')
    t=(near or pk)[0]['tag']; await pg.mouse.move(*S(t['x']+t['w']/2,t['y']+t['h']/2)); await pg.wait_for_timeout(200)
    ok(await ev("window.__tsrqPeakHover()"),'passando sopra l\'etichetta: anteprima attiva')
    await pg.screenshot(path='nw_peak_hover.png')
    sx,sy=S(t['x']+t['w']/2,t['y']+t['h']/2); await pg.mouse.down(); await pg.mouse.move(sx,sy+60,steps=8); await pg.mouse.up(); await pg.wait_for_timeout(250)
    bs=await bands(); f0=(near or pk)[0]['f']
    ok(len(bs)==1 and bs[0]['t']==0 and abs(bs[0]['f']-f0)/f0<0.01 and abs(bs[0]['q']-6)<1e-9 and bs[0]['g']<-1,f"clic + trascina giu: Bell sul picco che taglia ({bs})")
    await pg.screenshot(path='nw_peak_cut.png')
    await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(150); b=await bands(); ok(len(b)==1 and abs(b[0]['g'])<1e-9 and abs(b[0]['q']-6)<1e-9,f'undo 1: banda a 0 dB con Q 6 ({b})')
    await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(150); ok(len(await bands())==0,'undo 2: nessuna banda')
    ok(not errs,f'nessun errore JavaScript ({errs})')
    await br.close()
  print(f'RISULTATO nuove funzioni UI: {sum(res)} PASS, {len(res)-sum(res)} FAIL'); sys.exit(0 if all(res) else 1)
asyncio.run(main())
